export const FIREBASE_VISION_API_KEY = "AIzaSyD2s5j_clEQunOP56eT1_q_I9pzsVSZmmc"
export const FIREBASE_AUTH_API_KEY = "AIzaSyDAxm__c6audTDu0i0TixJGQ9UrOi87CB4"
export const FIREBASE_DATABASE_URL = "https://inventorya-b09e5-default-rtdb.firebaseio.com"
export const FIREBASE_PROJECT_ID = "inventorya-b09e5"
export const FIREBASE_MESSAGING_SENDER_ID = "387122632886"
export const FIREBASE_AUTH_DOMAIN = "inventorya-b09e5.firebaseapp.com"
export const FIREBASE_STORAGE_BUCKET = "inventorya-b09e5.appspot.com"